### ISSUE TITLE
Can't connect to ports 80, 443; it seems that docker listens only on IPv6

### ISSUE THREAD

**Issue by skaurus** [oblique/proxflix#2]
Hi,

I've just installed your docker image on my server (thanks!)

My router set in a way that DNS resolves pandora.com to an IP address of this server, but curl can't get it:

    $ curl -v -o /dev/null https://www.pandora.com
    * Rebuilt URL to: https://www.pandora.com/
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
      0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying server-ip...
    *   Trying server-ip6...
    * connect to server-ip6 port 443 failed: Connection refused
      0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0* connect to server-ip port 443 failed: Connection refused
    * Failed to connect to www.pandora.com port 443: Connection refused
    * Closing connection 0
    curl: (7) Failed to connect to www.pandora.com port 443: Connection refused

I tried to telnet to server-ip, ports 53, 80, 443, but I can't: `Connection refused`.
I have disabled iptables in your image: `proxflix config-set iptables false` (and restarted it), and I have following ufw rules:

    Status: active
    Logging: on (low)
    Default: deny (incoming), allow (outgoing), allow (routed)
    New profiles: skip

    To                         Action      From
    --                         ------      ----
    22/tcp                     ALLOW IN    Anywhere
    80,443/tcp                 ALLOW IN    my-public-ip
    53/udp                     ALLOW IN    my-public-ip
    80,443/tcp                 ALLOW IN    Anywhere
    53/udp                     ALLOW IN    Anywhere
    22/tcp (v6)                ALLOW IN    Anywhere (v6)
    80,443/tcp (v6)            ALLOW IN    Anywhere (v6)
    53/udp (v6)                ALLOW IN    Anywhere (v6)

There is no entries in ufw log about blocked requests from my home ip.
Also netstat output from the server:

    $ sudo netstat -tulpn
    sudo: unable to resolve host srv.skaur.us
    Active Internet connections (only servers)
    Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
    tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      19134/sshd
    tcp6       0      0 :::80                   :::*                    LISTEN      32114/docker-proxy
    tcp6       0      0 :::53                   :::*                    LISTEN      32126/docker-proxy
    tcp6       0      0 :::22                   :::*                    LISTEN      19134/sshd
    tcp6       0      0 :::443                  :::*                    LISTEN      32102/docker-proxy
    udp6       0      0 :::53                   :::*                                32138/docker-proxy

Do I misunderstand something? What do I have to do so I can connect to http and dns ports of my server?

**Comment by oblique** [comment]
Give me the output of the following commands while proxflix is running:

```
docker ps
iptables -S
iptables -S -t nat
```

Have you tried to disable ufw?

**Comment by skaurus** [comment]
Hmm, I restarted the server and problem went away. Sorry that I did bother you! And thanks for your work again :-)
